spring.application.name=Task_3
FirstName =
LastName = 
ID=
Instance = 1

spring.data.mongodb.uri=mongodb://root:example@localhost:27017/<ahmed_52_2383>?authSource=admin
spring.data.mongodb.database=<ahmed_52_2383>
